"use client";
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "en" | "fr";

type TParams = Record<string, string | number>;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string, params?: TParams) => string;
  dateLocale: string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  dateLocale: "en-CA",
});

export const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    "nav.features": "Features",
    "nav.how": "How it works",
    "nav.pricing": "Pricing",
    "nav.login": "Log in",
    "nav.start": "Start Free",

    // Hero
    "hero.badge": "ALL-IN-ONE CYBERSECURITY PLATFORM",
    "hero.tagline": "Scan. Secure. Comply.",
    "hero.title1": "The cybersecurity platform",
    "hero.title2": "for Canadian",
    "hero.title3": "IT consultants",
    "hero.subtitle": "Scan your clients' attack surface, generate compliance policies, export professional reports — in 20 minutes per client.",
    "hero.cta": "Scan my domain",
    "hero.demo": "See how it works",
    "hero.badge1": "Loi 25 & PIPEDA",
    "hero.badge2": "MSPs & IT Consultants",
    "hero.badge3": "NIST · CIS · ISO 27001",

    // Preview card
    "hero.preview.domain": "acme-corp.com",
    "hero.preview.score": "Risk Score",
    "hero.preview.risk": "MEDIUM Risk",
    "hero.preview.finding1": "3 compromised emails detected (HIBP)",
    "hero.preview.finding2": "SSL expires in 12 days",
    "hero.preview.finding3": "SPF & DMARC configured",

    // Standards
    "standards.title": "Aligned with industry standards",

    // How it works
    "how.title": "A complete workflow in 4 steps",
    "how.subtitle": "From diagnosis to delivery, everything is integrated.",
    "how.step1.title": "Attack Surface Diagnostic",
    "how.step1.desc": "Passive scan of your domain: SSL, DNS, compromised emails (HIBP), exposed subdomains.",
    "how.step2.title": "Security Score + NIST/CIS/ISO",
    "how.step2.desc": "Instant score with compliance control mapping and gap identification.",
    "how.step3.title": "Automatic Policy Generation",
    "how.step3.desc": "AI-generated professional policies, tailored to the detected vulnerabilities.",
    "how.step4.title": "Multi-format Export",
    "how.step4.desc": "PDF, Word, Confluence and Notion — ready to deliver to your clients or auditors.",

    // Features
    "features.title": "Everything you need",
    "features.subtitle": "Professional cybersecurity, simplified for consultants and MSPs.",
    "features.1.title": "Real-time Domain Scan",
    "features.1.desc": "SSL, DNS, HIBP, subdomains — complete analysis with no extra tools",
    "features.2.title": "Instant Risk Score",
    "features.2.desc": "0–100 score with LOW/MEDIUM/HIGH risk level and improvement areas",
    "features.3.title": "5 Policy Types",
    "features.3.desc": "Password, Backup, Incident Response, Acceptable Use, Remote Work",
    "features.4.title": "NIST · CIS · ISO 27001 Alignment",
    "features.4.desc": "Each policy mapped to compliance controls with precise references",
    "features.5.title": "PDF + Word Export",
    "features.5.desc": "Professional documents with logo, version, table of contents — ready to deliver",
    "features.6.title": "Loi 25 & PIPEDA Ready",
    "features.6.desc": "Policies aligned with Canadian privacy laws and SMB compliance needs",

    // Pricing
    "pricing.title": "Simple, transparent pricing",
    "pricing.subtitle": "No hidden fees. Cancel anytime. Save ~17% (2 months free) with annual billing.",
    "pricing.subtitleBeta": "We're in beta — every feature is free while we build this with early users like you.",
    "pricing.annualNote": "Prices shown monthly. Annual billing available at checkout — 2 months free (~17% off).",
    "pricing.annualNoteBeta": "Paid plans (Starter, Pro, Agency) are coming soon — beta users get everything free in the meantime.",
    "pricing.starter.name": "Starter",
    "pricing.starter.price": "$59",
    "pricing.starter.period": "/month",
    "pricing.starter.desc": "For solo consultants working with a single client.",
    "pricing.starter.cta": "Get started",
    "pricing.starter.f1": "1 client",
    "pricing.starter.f2": "Attack surface scan",
    "pricing.starter.f3": "Security score",
    "pricing.starter.f4": "AI-generated policies",
    "pricing.starter.f5": "PDF & Word export",
    "pricing.pro.name": "Pro",
    "pricing.pro.badge": "Most popular",
    "pricing.pro.price": "$149",
    "pricing.pro.period": "/month",
    "pricing.pro.desc": "For consultants managing a handful of clients.",
    "pricing.pro.cta": "Get started",
    "pricing.pro.f1": "5 clients",
    "pricing.pro.f2": "Everything in Starter",
    "pricing.pro.f3": "Custom branding on exports",
    "pricing.pro.f4": "Policy versioning & regeneration",
    "pricing.pro.f5": "Confluence & Notion export",
    "pricing.agency.name": "Agency",
    "pricing.agency.price": "$299",
    "pricing.agency.period": "/month",
    "pricing.agency.desc": "For agencies and MSPs managing a full client roster.",
    "pricing.agency.cta": "Get started",
    "pricing.agency.f1": "Unlimited clients",
    "pricing.agency.f2": "Everything in Pro",
    "pricing.agency.f3": "Full white-label client portal",
    "pricing.agency.f4": "Multiple team members",
    "pricing.agency.f5": "Priority support",
    "pricing.beta.name": "Beta",
    "pricing.beta.badge": "Limited time",
    "pricing.beta.price": "Free",
    "pricing.beta.period": "",
    "pricing.beta.desc": "Everything, free — in exchange for feedback, calls, and a testimonial.",
    "pricing.beta.cta": "Join the beta",
    "pricing.beta.f1": "Unlimited clients",
    "pricing.beta.f2": "Every feature, unlocked",
    "pricing.beta.f3": "Direct line to our team",
    "pricing.beta.f4": "Shape the roadmap",
    "pricing.beta.f5": "Limited-time offer",

    // CTA
    "cta.title": "Start your first diagnostic",
    "cta.subtitle": "Scan your domain and get your first compliance policies in under 20 minutes.",
    "cta.button": "Scan my domain — Free",

    // Footer
    "footer.copy": "© 2026 SecurePilot. Built for Canadian IT consultants & MSPs.",

    // Dashboard nav
    "dash.nav.dashboard": "Dashboard",
    "dash.nav.scan": "Diagnostic",
    "dash.nav.policies": "Policies",
    "dash.nav.generate": "Generate Policy",
    "dash.nav.clients": "Clients",
    "dash.nav.securityScore": "Security Score",
    "dash.nav.auditEvidence": "Audit Evidence",
    "dash.nav.frameworks": "Frameworks",
    "dash.nav.settings": "Settings",
    "dash.nav.logout": "Logout",

    // Topbar / client switcher
    "dash.topbar.notifications": "Notifications",
    "dash.topbar.markAllRead": "Mark all read",
    "dash.topbar.caughtUp": "You're all caught up.",
    "dash.client.select": "Select a client",
    "dash.client.manage": "Manage clients",

    // Clients list
    "clients.title": "Clients",
    "clients.limitUnlimited": "Unlimited clients on your plan.",
    "clients.limitUsed.one": "{count} / {limit} client used on your {plan} plan.",
    "clients.limitUsed.other": "{count} / {limit} clients used on your {plan} plan.",
    "clients.add": "Add Client",
    "clients.limitReached": "You've reached your plan's client limit.",
    "clients.upgrade": "Upgrade your plan",
    "clients.toAddMore": "to add more clients.",
    "clients.namePlaceholder": "Client or company name",
    "clients.create": "Create",
    "clients.empty": "No clients yet. Add your first one to get started.",
    "clients.added": "Added {date}",
    "clients.createFailed": "Failed to create client.",
    "clients.created": "Client created.",
    "clients.deleteConfirm": "Delete this client and all of their policies, scans, and registers? This cannot be undone.",
    "clients.deleteFailed": "Failed to delete client.",
    "clients.deleted": "Client deleted.",
    "clients.genericError": "Something went wrong.",

    // Client profile
    "clientProfile.back": "Back to clients",
    "clientProfile.subtitle": "Company and security profile used to generate this client's policies.",
    "clientProfile.tab.company": "Company Information",
    "clientProfile.tab.security": "Security Information",
    "clientProfile.companyName": "Company Name",
    "clientProfile.website": "Website (optional)",
    "clientProfile.industry": "Industry",
    "clientProfile.selectIndustry": "Select industry",
    "clientProfile.employeeCount": "Number of Employees",
    "clientProfile.selectRange": "Select range",
    "clientProfile.phone": "Phone",
    "clientProfile.email": "Email",
    "clientProfile.country": "Country",
    "clientProfile.province": "Province / State",
    "clientProfile.cloudServices": "Cloud Services",
    "clientProfile.remoteWork": "Remote Work",
    "clientProfile.microsoft365": "Microsoft 365",
    "clientProfile.googleWorkspace": "Google Workspace",
    "clientProfile.mfaEnabled": "MFA Enabled",
    "clientProfile.hasBackups": "Backups in place",
    "clientProfile.hasItDept": "IT Department / External MSP",
    "clientProfile.personalDevices": "Employees use personal devices",
    "clientProfile.save": "Save Changes",
    "clientProfile.saveFailed": "Failed to save profile.",
    "clientProfile.saved": "Profile saved!",
    "clientProfile.industry.accounting": "Accounting",
    "clientProfile.industry.construction": "Construction",
    "clientProfile.industry.consulting": "Consulting",
    "clientProfile.industry.education": "Education",
    "clientProfile.industry.finance": "Finance",
    "clientProfile.industry.healthcare": "Healthcare",
    "clientProfile.industry.hospitality": "Hospitality",
    "clientProfile.industry.itWeb": "IT / Web Agency",
    "clientProfile.industry.legal": "Legal",
    "clientProfile.industry.manufacturing": "Manufacturing",
    "clientProfile.industry.realEstate": "Real Estate",
    "clientProfile.industry.retail": "Retail",
    "clientProfile.industry.other": "Other",
    "clientProfile.cloud.none": "None",
    "clientProfile.cloud.mixed": "Mixed / Multiple",
    "clientProfile.country.canada": "Canada",
    "clientProfile.country.us": "United States",

    // Choose plan
    "plan.changeTitle": "Change your plan",
    "plan.chooseTitle": "Choose your plan",
    "plan.changeSubtitle": "Switch plans anytime — changes apply immediately.",
    "plan.chooseSubtitle": "Pick a plan to unlock your dashboard. You can change it anytime.",
    "plan.monthly": "Monthly",
    "plan.annual": "Annual",
    "plan.twoMonthsFree": "2 months free",
    "plan.perMonth": "/mo",
    "plan.free": "Free",
    "plan.billedPerYear": "Billed ${amount}/year",
    "plan.mostPopular": "MOST POPULAR",
    "plan.limitedTime": "LIMITED TIME",
    "plan.unlimitedClients": "Unlimited clients",
    "plan.clientCount.one": "{count} client",
    "plan.clientCount.other": "{count} clients",
    "plan.current": "Current plan",
    "plan.saving": "Saving…",
    "plan.joinBeta": "Join the beta",
    "plan.choose": "Choose {name}",
    "plan.selectFailed": "Failed to select plan.",
    "plan.onPlan": "You're on the {name} plan.",
    "plan.checkoutFailed": "Failed to start checkout.",
    "plan.genericError": "Something went wrong.",
    "plan.tagline.starter": "For solo consultants working with a single client.",
    "plan.tagline.pro": "For consultants managing a handful of clients.",
    "plan.tagline.agency": "For agencies and MSPs managing a full client roster.",
    "plan.tagline.beta": "Everything, free — in exchange for feedback, calls, and a testimonial.",
    "plan.include.scan": "Attack surface scan",
    "plan.include.score": "Security score",
    "plan.include.aiPolicies": "AI-generated policies",
    "plan.include.export": "PDF & Word export",
    "plan.feature.branding": "Custom branding on exports",
    "plan.feature.versioning": "Policy versioning & regeneration",
    "plan.feature.confluence_notion": "Confluence & Notion export",
    "plan.feature.white_label": "Full white-label client portal",
    "plan.feature.multi_user": "Multiple team members",
    "plan.feature.priority_support": "Priority support",

    // Dashboard
    "dashboard.scanBanner.title": "Security diagnostic",
    "dashboard.scanBanner.subtitle": "Analyze your domain's attack surface in 30 seconds.",
    "dashboard.scanBanner.cta": "Run the scan",
    "dashboard.greeting": "Good morning, {name}! 👋",
    "dashboard.subtitle": "Here's an overview of your security.",
    "dashboard.generateNew": "Generate New Policy",
    "dashboard.policiesGenerated": "Policies Generated",
    "dashboard.viewAllPolicies": "View all policies →",
    "dashboard.securityScore": "Security Score",
    "dashboard.viewDetails": "View details →",
    "dashboard.recommendations": "Recommendations",
    "dashboard.viewRecommendations": "View recommendations →",
    "dashboard.recentPolicies": "Recent Policies",
    "dashboard.viewAll": "View All",
    "dashboard.noPolicies": "No policies yet. Generate your first one!",
    "dashboard.generatePolicy": "Generate Policy",
    "dashboard.versionDate": "Version {version} · {date}",
    "dashboard.topRecommendations": "Top Recommendations",
    "dashboard.noRecommendations": "Generate a policy to see recommendations.",
    "dashboard.viewAllRecommendations": "View All Recommendations →",
    "dashboard.needsReview.one": "{count} policy needs a review",
    "dashboard.needsReview.other": "{count} policies need a review",
    "dashboard.frameworkUpdated": "A framework you're aligned with was updated since generation. Review the affected policies.",
    "dashboard.reviewNow": "Review now →",
    "dashboard.completeProfile": "Complete your company profile",
    "dashboard.completeProfileDesc": "Add your company details for more accurate and personalized policies.",
    "dashboard.setUpProfile": "Set up profile →",

    // Policies list
    "policiesPage.title": "Policies",
    "policiesPage.subtitle": "Manage and view your security policies.",
    "policiesPage.generateNew": "Generate New Policy",
    "policiesList.search": "Search policies…",
    "policiesList.name": "Policy Name",
    "policiesList.status": "Status",
    "policiesList.lastUpdated": "Last Updated",
    "policiesList.actions": "Actions",
    "policiesList.noMatch": "No policies match your search.",
    "policiesList.none": "No policies yet.",
    "policiesList.version": "Version {version}",
    "policiesList.rename": "Rename",
    "policiesList.delete": "Delete",
    "policiesList.save": "Save",
    "policiesList.cancel": "Cancel",
    "policiesList.deleteConfirm": "Delete this policy? This cannot be undone.",
    "policiesList.deleteFailed": "Failed to delete.",
    "policiesList.deleted": "Policy deleted.",
    "policiesList.renameFailed": "Failed to rename.",
    "policiesList.renamed": "Renamed.",

    // Scan
    "scan.stage1": "Checking SSL…",
    "scan.stage2": "Analyzing data leaks…",
    "scan.stage3": "Scanning DNS…",
    "scan.stage4": "Generating report…",
    "scan.invalidDomain": "Enter a valid domain (e.g. company.com).",
    "scan.failed": "The diagnostic failed.",
    "scan.genericError": "Something went wrong.",
    "scan.scanningTitle": "Diagnostic in progress…",
    "scan.scanningNote": "This can take up to 30 seconds.",
    "scan.title": "Attack surface diagnostic",
    "scan.subtitle": "Analyze your domain's attack surface: SSL certificate, data leaks, DNS configuration and exposed subdomains.",
    "scan.domainLabel": "Domain to analyze",
    "scan.domainPlaceholder": "company.com",
    "scan.launch": "Run the diagnostic",
    "scan.report.scannedOn": "Scanned on {date}",
    "scan.report.newScan": "New scan",
    "scan.report.ssl": "SSL",
    "scan.report.grade": "Grade: {grade}",
    "scan.report.certExpired": "Certificate expired",
    "scan.report.expiresIn": "Expires in {days} days",
    "scan.report.expiryUnknown": "Unknown expiry",
    "scan.report.noSSL": "No SSL certificate detected",
    "scan.report.dataLeaks": "Data leaks",
    "scan.report.compromisedAccounts.one": "{count} compromised account",
    "scan.report.compromisedAccounts.other": "{count} compromised accounts",
    "scan.report.dns": "DNS",
    "scan.report.subdomains": "Subdomains",
    "scan.report.subdomainsExposed.one": "{count} exposed subdomain",
    "scan.report.subdomainsExposed.other": "{count} exposed subdomains",
    "scan.report.findings": "Diagnostic findings",
    "scan.report.recommendedPolicies": "Recommended policies",
    "scan.report.basedOn": "Based on vulnerabilities detected during the diagnostic.",
    "scan.report.urgent": "Urgent",
    "scan.report.generate": "Generate",
    "scan.risk.low": "LOW Risk",
    "scan.risk.medium": "MEDIUM Risk",
    "scan.risk.high": "HIGH Risk",
    "scan.policy.password.label": "Password Policy",
    "scan.policy.password.desc": "Complexity requirements, expiration and password management.",
    "scan.policy.incidentResponse.label": "Incident Response Plan",
    "scan.policy.incidentResponse.desc": "Procedure to follow in case of a security incident.",
    "scan.policy.backup.label": "Backup Policy",
    "scan.policy.backup.desc": "Frequency, location and restore testing of backups.",
    "scan.policy.acceptableUse.label": "Acceptable Use Policy",
    "scan.policy.acceptableUse.desc": "Rules for using the company's technology resources.",
    "scan.policy.remoteWork.label": "Remote Work Policy",
    "scan.policy.remoteWork.desc": "Securing remote access and off-site devices.",

    // Audit evidence — page & PDF
    "audit.pageTitle": "Audit Evidence",
    "audit.pageSubtitle": "Maintain the registers auditors and cyber insurers ask for, and export a complete audit package for {companyName}.",
    "audit.generating": "Generating…",
    "audit.generateFullReport": "Generate Full Audit Report",
    "audit.reportFailed": "Failed to generate the audit report. Please try again.",
    "audit.pdf.title": "Security Audit Package",
    "audit.pdf.generatedOn": "Generated on {date}",
    "audit.pdf.companyProfile": "1. Company Profile",
    "audit.pdf.industry": "Industry",
    "audit.pdf.employees": "Employees",
    "audit.pdf.countryProvince": "Country / Province",
    "audit.pdf.mfaEnabled": "MFA Enabled",
    "audit.pdf.backupsInPlace": "Backups in Place",
    "audit.pdf.itDeptMsp": "IT Department / MSP",
    "audit.pdf.activePolicies": "2. Active Security Policies",
    "audit.pdf.policy": "Policy",
    "audit.pdf.version": "Version",
    "audit.pdf.status": "Status",
    "audit.pdf.securityScore": "Security Score",
    "audit.pdf.lastUpdated": "Last Updated",
    "audit.pdf.yes": "Yes",
    "audit.pdf.no": "No",
    "audit.pdf.footer": "{companyName} — Security Audit Package — CONFIDENTIAL",

    // Audit registers
    "register.unsavedChanges": "Unsaved changes",
    "register.addRow": "Add Row",
    "register.save": "Save",
    "register.saving": "Saving…",
    "register.saved": "{title} saved.",
    "register.saveFailed": "Failed to save. Please try again.",
    "register.empty": "No entries yet. Click \"Add Row\" to start building this register.",
    "register.exportPDF": "Export PDF",
    "register.pdfFooter": "{companyName} — Generated {date} — Confidential",
    "register.pdfFailed": "Failed to generate PDF. Please try again.",

    "artifact.title.backup_register": "Backup Register",
    "artifact.desc.backup_register": "Evidence of what data is backed up, how often, and where — required by most auditors and cyber insurers.",
    "artifact.title.asset_inventory": "Asset Inventory",
    "artifact.desc.asset_inventory": "A register of hardware, software, and cloud assets that store or process company data.",
    "artifact.title.training_register": "Security Training Register",
    "artifact.desc.training_register": "Proof that employees completed security awareness training — commonly requested during audits.",
    "artifact.title.incident_register": "Incident Register",
    "artifact.desc.incident_register": "Log of security incidents, their severity, and resolution — required by most incident response and breach-notification obligations.",
    "artifact.title.access_register": "Access Register",
    "artifact.desc.access_register": "Record of who has access to which systems and why — evidence that access is granted, reviewed, and revoked deliberately.",
    "artifact.title.rights_request_register": "Data Subject Rights Requests Register",
    "artifact.desc.rights_request_register": "Log of access, rectification, erasure, and portability requests — evidence of compliance with Law 25 / GDPR data subject rights obligations.",
    "artifact.title.third_party_register": "Third-Party / Vendor Register",
    "artifact.desc.third_party_register": "Inventory of vendors and service providers that access or process company data, and their contractual safeguards.",

    "artifact.col.systemData": "System / Data",
    "artifact.col.frequency": "Frequency",
    "artifact.col.storageLocation": "Storage Location",
    "artifact.col.retentionPeriod": "Retention Period",
    "artifact.col.encrypted": "Encrypted",
    "artifact.col.lastRestoreTest": "Last Restore Test",
    "artifact.col.assetName": "Asset Name",
    "artifact.col.category": "Category",
    "artifact.col.owner": "Owner",
    "artifact.col.criticality": "Criticality",
    "artifact.col.notes": "Notes",
    "artifact.col.employee": "Employee",
    "artifact.col.trainingTopic": "Training / Topic",
    "artifact.col.completedOn": "Completed On",
    "artifact.col.nextDue": "Next Due",
    "artifact.col.date": "Date",
    "artifact.col.description": "Description",
    "artifact.col.severity": "Severity",
    "artifact.col.affectedSystems": "Affected Systems",
    "artifact.col.reportedBy": "Reported By",
    "artifact.col.status": "Status",
    "artifact.col.resolutionDate": "Resolution Date",
    "artifact.col.employeeUser": "Employee / User",
    "artifact.col.systemResource": "System / Resource",
    "artifact.col.accessLevel": "Access Level",
    "artifact.col.grantedDate": "Granted Date",
    "artifact.col.grantedBy": "Granted By",
    "artifact.col.lastReviewed": "Last Reviewed",
    "artifact.col.revokedDate": "Revoked Date",
    "artifact.col.dateReceived": "Date Received",
    "artifact.col.requester": "Requester",
    "artifact.col.requestType": "Request Type",
    "artifact.col.responseDate": "Response Date",
    "artifact.col.vendorName": "Vendor Name",
    "artifact.col.serviceProvided": "Service Provided",
    "artifact.col.dataAccessLevel": "Data Access Level",
    "artifact.col.contractDate": "Contract Date",
    "artifact.col.dpaSigned": "DPA Signed",

    "artifact.opt.realTime": "Real-time",
    "artifact.opt.daily": "Daily",
    "artifact.opt.weekly": "Weekly",
    "artifact.opt.monthly": "Monthly",
    "artifact.opt.yes": "Yes",
    "artifact.opt.no": "No",
    "artifact.opt.hardware": "Hardware",
    "artifact.opt.software": "Software",
    "artifact.opt.cloudService": "Cloud Service",
    "artifact.opt.data": "Data",
    "artifact.opt.low": "Low",
    "artifact.opt.medium": "Medium",
    "artifact.opt.high": "High",
    "artifact.opt.critical": "Critical",
    "artifact.opt.open": "Open",
    "artifact.opt.inProgress": "In Progress",
    "artifact.opt.resolved": "Resolved",
    "artifact.opt.completed": "Completed",
    "artifact.opt.denied": "Denied",
    "artifact.opt.access": "Access",
    "artifact.opt.rectification": "Rectification",
    "artifact.opt.erasure": "Erasure",
    "artifact.opt.portability": "Portability",
    "artifact.opt.objection": "Objection",
    "artifact.opt.none": "None",
    "artifact.opt.limited": "Limited",
    "artifact.opt.full": "Full",

    // Policy detail page
    "policyDetail.regenerate": "Regenerate",
    "policyDetail.regeneratePro": "Regenerate (Pro)",
    "policyDetail.docInfo": "Document Information",
    "policyDetail.policyOwner": "Policy Owner",
    "policyDetail.itDepartment": "IT Department",
    "policyDetail.reviewDate": "Review Date",
    "policyDetail.nextReview": "Next Review",
    "policyDetail.in12Months": "In 12 months",
    "policyDetail.version": "Version",
    "policyDetail.outOf100": "out of 100",
    "policyDetail.viewFullReport": "View full security report →",
    "tabs.document": "Document",
    "tabs.versionHistory": "Version History",
    "sidebar.auditEvidence.desc": "Registers to maintain to prove compliance with this policy.",
    "sidebar.auditEvidence.manage": "Manage registers →",
    "sidebar.bestPractices.title": "Best Practices",
    "sidebar.bestPractices.dos": "✅ Do",
    "sidebar.bestPractices.donts": "❌ Don't",
    "sidebar.actionChecklist.title": "Priority Actions",
    "sidebar.actionChecklist.completed": "{done}/{total} completed",
    "sidebar.actionChecklist.priority.high": "High",
    "sidebar.actionChecklist.priority.medium": "Medium",
    "sidebar.actionChecklist.priority.low": "Low",
    "complianceBadges.alignedWith": "Aligned with:",
    "sidebar.policyImportance.title": "Why this policy matters",
    "sidebar.policyImportance.oftenRequired": "Often required by",
    "sidebar.clientPortal.title": "Client Portal",
    "sidebar.clientPortal.desc": "Share a read-only link so your client can view this policy without an account.",
    "sidebar.clientPortal.linkEnabled": "Link enabled",
    "sidebar.clientPortal.linkDisabled": "Link disabled",
    "sidebar.clientPortal.copyLink": "Copy link",
    "sidebar.clientPortal.enabled": "Client portal link enabled.",
    "sidebar.clientPortal.disabled": "Client portal link disabled.",
    "sidebar.clientPortal.updateFailed": "Failed to update the client portal link.",
    "exportWorkspace.exporting": "Exporting…",
    "exportWorkspace.exportTo": "Export to {provider}",
    "exportWorkspace.exportFailed": "Failed to export to {provider}.",
    "exportWorkspace.exported": "Exported to {provider}.",
    "exportWorkspace.openPage": "Open page",
    "exportWorkspace.genericError": "Something went wrong.",
    "versionHistory.backToList": "Back to version list",
    "versionHistory.restoreThis": "Restore this version",
    "versionHistory.restoring": "Restoring…",
    "versionHistory.restoreFailed": "Restore failed",
    "versionHistory.restored": "Restored to v{version}.0",
    "versionHistory.genericError": "Something went wrong.",
    "versionHistory.current": "Current",
    "versionHistory.change.generated": "Generated",
    "versionHistory.change.regenerated": "Regenerated",
    "versionHistory.change.restored": "Restored",

    // Security score page
    "securityScore.subtitle.one": "Based on {count} generated policy.",
    "securityScore.subtitle.other": "Based on {count} generated policies.",
    "securityScore.noScoreTitle": "No Security Score Yet",
    "securityScore.noScoreDesc": "Generate your first security policy and we'll automatically calculate your security score with strengths, weaknesses, and recommendations.",
    "securityScore.generateFirst": "Generate First Policy",
    "securityScore.execSummary": "Executive Summary",
    "securityScore.maturityLevel": "Maturity Level",
    "securityScore.strengths": "Strengths",
    "securityScore.weaknesses": "Weaknesses",
    "securityScore.scoreHistory": "Score History",
    "securityScore.scoreHistoryDesc": "How each policy's security score has evolved across regenerations.",
    "securityScore.overVersions": "over {count} versions",
    "securityScore.actionPlan": "Prioritized Action Plan",
    "securityScore.gapAnalysis": "Gap Analysis",
    "securityScore.gapAnalysisDesc": "Based on your most recently generated policy.",
    "securityScore.currentCompliance": "Current Compliance",
    "securityScore.missingControls": "Missing Controls",
    "securityScore.associatedRisk": "Associated Risk",
    "securityScore.recommendations": "Prioritized Recommendations",
    "securityScore.missingPolicies": "Missing Policies",
    "securityScore.generateMissing": "Generate missing policies",
    "securityScore.ring.good": "Good",
    "securityScore.ring.fair": "Fair",
    "securityScore.ring.poor": "Poor",
    "securityScore.priority.high": "High Priority",
    "securityScore.priority.medium": "Medium Priority",
    "securityScore.priority.low": "Low Priority",
    "securityScore.maturity.basic": "Basic",
    "securityScore.maturity.developing": "Developing",
    "securityScore.maturity.defined": "Defined",
    "securityScore.maturity.advanced": "Advanced",

    // Frameworks page
    "frameworks.title": "Frameworks Dashboard",
    "frameworks.subtitle": "Compliance coverage across every framework your policies are aligned with.",
    "frameworks.outdatedBadge": "Outdated",
    "frameworks.policyCount.one": "{count} policy",
    "frameworks.policyCount.other": "{count} policies",
    "frameworks.affectedNotice.one": "{count} policy references an outdated framework revision",
    "frameworks.affectedNotice.other": "{count} policies reference an outdated framework revision",
    "frameworks.affectedDesc": "A framework you're aligned with has been updated since your policy was generated. Regenerate the affected policies below to bring them current.",
    "frameworks.currentVersion": "Current version: {version}",
    "frameworks.relevantFor": "Relevant for",
    "frameworks.relatedPolicies": "Related policies",
    "frameworks.affectedListIntro": "{count} of your policies reference an older revision:",
    "frameworks.update": "Update",
    "frameworks.effort": "Effort",
    "frameworks.effort.high": "High",
    "frameworks.effort.medium": "Medium",
    "frameworks.effort.lowMedium": "Low to Medium",
    "frameworks.footerTitle": "SecurePilot automatically aligns your policies",
    "frameworks.footerDesc": "Every generated policy is automatically mapped to applicable frameworks (NIST, CIS, ISO 27001, SOC 2, Law 25, GDPR) based on your company context, and flagged here if the underlying standard is updated.",

    "fw.iso27001.tagline": "Information Security Management System",
    "fw.iso27001.desc": "International standard defining requirements for establishing, implementing, maintaining and improving an information security management system (ISMS). Recognized worldwide and frequently required in enterprise RFPs and procurement processes.",
    "fw.iso27001.relevant1": "Formal certification",
    "fw.iso27001.relevant2": "Enterprise clients",
    "fw.iso27001.relevant3": "Government procurement",
    "fw.iso27001.policy1": "Password Policy",
    "fw.iso27001.policy2": "Access Control",
    "fw.iso27001.policy3": "Incident Response",
    "fw.iso27001.policy4": "Business Continuity",

    "fw.nist.tagline": "National Institute of Standards and Technology Cybersecurity Framework",
    "fw.nist.desc": "Voluntary U.S. framework organized around 5 functions: Identify, Protect, Detect, Respond, Recover. Widely adopted in North America, particularly by SMBs that want to structure their security posture without pursuing formal certification.",
    "fw.nist.relevant1": "North American SMBs",
    "fw.nist.relevant2": "Financial sector",
    "fw.nist.relevant3": "Critical infrastructure",
    "fw.nist.policy1": "Backup Policy",
    "fw.nist.policy2": "Incident Response Plan",
    "fw.nist.policy3": "Access Management",

    "fw.cis.tagline": "Center for Internet Security — 18 prioritized controls",
    "fw.cis.desc": "18 concrete, prioritized controls to reduce cyber risk. Ideal for SMBs getting started: begin with Implementation Group 1 (IG1) controls to cover 85% of common attacks with minimal effort and resources.",
    "fw.cis.relevant1": "SMBs getting started",
    "fw.cis.relevant2": "Quick security wins",
    "fw.cis.relevant3": "Limited IT resources",
    "fw.cis.policy1": "Asset Inventory",
    "fw.cis.policy2": "Secure Configuration",
    "fw.cis.policy3": "Privileged Access Control",

    "fw.soc2.tagline": "Service Organization Control — Trust, Security, Availability",
    "fw.soc2.desc": "Audit report based on 5 Trust Service Criteria: Security, Availability, Processing Integrity, Confidentiality, and Privacy. Highly requested by SaaS clients and technology companies to demonstrate operational rigor to their customers.",
    "fw.soc2.relevant1": "SaaS companies",
    "fw.soc2.relevant2": "Cloud service providers",
    "fw.soc2.relevant3": "U.S. enterprise customers",
    "fw.soc2.policy1": "Logical Access Control",
    "fw.soc2.policy2": "Continuous Monitoring",
    "fw.soc2.policy3": "Change Management",

    "fw.loi25.tagline": "An Act to modernize legislative provisions as regards the protection of personal information (Quebec)",
    "fw.loi25.desc": "Quebec law in force since 2022 that strengthens the protection of personal information. It requires the appointment of a Privacy Officer, Privacy Impact Assessments (PIAs), and incident notification within 72 hours.",
    "fw.loi25.relevant1": "Quebec-based businesses",
    "fw.loi25.relevant2": "Any organization collecting data in Quebec",
    "fw.loi25.policy1": "Privacy Policy",
    "fw.loi25.policy2": "Incident Response Plan",
    "fw.loi25.policy3": "BYOD Policy",

    "fw.rgpd.tagline": "General Data Protection Regulation (Europe)",
    "fw.rgpd.desc": "European regulation applicable to any organization processing personal data of EU residents. Requires consent, data minimization, appropriate security measures, and breach notification within 72 hours.",
    "fw.rgpd.relevant1": "European customers",
    "fw.rgpd.relevant2": "International commerce",
    "fw.rgpd.relevant3": "Organizations with EU operations",
    "fw.rgpd.policy1": "Privacy Policy",
    "fw.rgpd.policy2": "Data Retention Policy",
    "fw.rgpd.policy3": "Incident Response Plan",

    // Generate policy page
    "generate.loadingPolicy": "Loading policy…",
    "generate.generatingTitle": "Generating your policy…",
    "generate.generatingDesc": "Our AI is crafting a professional {type} tailored to your business.",
    "generate.generatingTime": "This usually takes 15–30 seconds",
    "generate.scanBanner": "This policy type was recommended based on your domain diagnostic.",
    "generate.why.title": "Why are you generating this policy?",
    "generate.why.subtitle": "This helps our AI adapt the tone and sections to your specific context.",
    "generate.back": "Back",
    "generate.continue": "Continue",
    "generate.stepOf": "Step {current} of {total}",
    "generate.answerPlaceholder": "Type your answer…",
    "generate.next": "Next",
    "generate.regenerate": "Regenerate",
    "generate.generate": "Generate",
    "generate.pageTitle": "Generate Policy",
    "generate.pageSubtitle": "Choose the type of policy you want to generate.",
    "generate.policyNotFound": "Policy not found.",
    "generate.generationFailed": "Generation failed",
    "generate.genericError": "Something went wrong.",
    "generate.policy.password.desc": "Create a strong password policy for your team.",
    "generate.policy.backup.desc": "Define your data backup rules and recovery objectives.",
    "generate.policy.incidentResponse.desc": "Prepare your team for security incidents.",
    "generate.policy.acceptableUse.desc": "Set the rules for acceptable technology usage.",
    "generate.policy.remoteWork.desc": "Secure your remote workforce effectively.",
    "genReason.audit": "Internal or external audit",
    "genReason.insurance": "Cyber insurance requirement",
    "genReason.client": "Client or partner requirement",
    "genReason.certification": "Certification (ISO 27001, SOC 2…)",
    "genReason.internal": "Internal improvement",

    // Shared (client portal) policy page
    "shared.readOnly": "Read-only client portal",
    "shared.execSummary": "Executive Summary",
    "shared.footer": "This is a shared, read-only view generated with SecurePilot.",

    // Settings page
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account settings and preferences.",
    "settings.tab.profile": "Profile",
    "settings.tab.plan": "Plan & Billing",
    "settings.tab.branding": "Branding",
    "settings.tab.notifications": "Notifications",
    "settings.tab.password": "Password",
    "settings.tab.integrations": "Integrations",
    "settings.tab.danger": "Danger Zone",
    "settings.upsell.proFeature": "{feature} is a Pro feature",
    "settings.upsell.upgrade": "Upgrade your plan to unlock this.",
    "settings.upsell.viewPlans": "View plans",
    "settings.profile.title": "Profile Information",
    "settings.profile.fullName": "Full Name",
    "settings.profile.lastName": "Last Name",
    "settings.profile.email": "Email",
    "settings.profile.emailHint": "Email cannot be changed here. Contact support.",
    "settings.saveChanges": "Save Changes",
    "settings.profile.updated": "Profile updated!",
    "settings.plan.title": "Plan & Billing",
    "settings.plan.name": "{name} plan",
    "settings.plan.free": "Free",
    "settings.plan.perYear": "${amount}/year",
    "settings.plan.perMonth": "${amount}/month",
    "settings.plan.change": "Change Plan",
    "settings.plan.includedFeatures": "Included features",
    "settings.plan.coreOnly": "Core features only — upgrade to unlock more.",
    "settings.plan.loading": "Loading your plan…",
    "settings.branding.title": "Branding",
    "settings.branding.desc": "White-label your exported policies with your own agency branding instead of SecurePilot's. Applies to every client.",
    "settings.branding.name": "Brand Name",
    "settings.branding.nameHint": "Shown on PDF and Word cover pages instead of SecurePilot's default branding.",
    "settings.branding.color": "Primary Color",
    "settings.branding.logoUrl": "Logo URL (optional)",
    "settings.branding.logoHint": "A hosted image URL — square logos work best.",
    "settings.branding.logoPreviewAlt": "Brand logo preview",
    "settings.branding.save": "Save Branding",
    "settings.branding.saveFailed": "Failed to save branding. Your plan may not include this feature.",
    "settings.branding.saved": "Branding saved.",
    "settings.notifications.title": "Notifications",
    "settings.notifications.reviewReminders": "Policy review reminders",
    "settings.notifications.reviewRemindersDesc": "Get notified when a policy is due for review",
    "settings.notifications.scoreUpdates": "Security score updates",
    "settings.notifications.scoreUpdatesDesc": "Get notified when your security score changes",
    "settings.notifications.newRecs": "New recommendations",
    "settings.notifications.newRecsDesc": "Get notified when new recommendations are available",
    "settings.notifications.savePrefs": "Save Preferences",
    "settings.password.title": "Change Password",
    "settings.password.current": "Current Password",
    "settings.password.new": "New Password",
    "settings.password.confirm": "Confirm New Password",
    "settings.password.update": "Update Password",
    "settings.password.mismatch": "Passwords do not match.",
    "settings.password.tooShort": "Password must be at least 8 characters.",
    "settings.password.updated": "Password updated!",
    "settings.integrations.title": "Integrations",
    "settings.integrations.desc": "Export policies straight to your Notion or Confluence workspace.",
    "settings.notion.title": "Notion",
    "settings.notion.desc": "Create an integration at {link}, share your destination page with it, then paste the token and that page's ID below. Exported policies will be created as sub-pages under it.",
    "settings.notion.token": "Internal Integration Token",
    "settings.notion.parentPageId": "Parent Page ID",
    "settings.notion.parentPageIdHint": "The 32-character ID at the end of your Notion page URL.",
    "settings.notion.save": "Save Notion Settings",
    "settings.notion.saveFailed": "Failed to save Notion settings.",
    "settings.notion.saved": "Notion connected.",
    "settings.confluence.title": "Confluence",
    "settings.confluence.desc": "Generate an API token at {link}. Exported policies will be created as pages in the space below.",
    "settings.confluence.siteUrl": "Site URL",
    "settings.confluence.accountEmail": "Account Email",
    "settings.confluence.apiToken": "API Token",
    "settings.confluence.spaceKey": "Space Key",
    "settings.confluence.save": "Save Confluence Settings",
    "settings.confluence.saveFailed": "Failed to save Confluence settings.",
    "settings.confluence.saved": "Confluence connected.",
    "settings.danger.title": "Danger Zone",
    "settings.danger.desc": "Once you delete your account, there is no going back. All your data will be permanently erased.",
    "settings.danger.delete": "Delete Account",
    "settings.danger.confirm": "Are you absolutely sure? This will permanently delete your account and all data. This cannot be undone.",
    "settings.danger.contactSupport": "Please contact support to delete your account.",

    // Relative time
    "time.justNow": "just now",
    "time.minutesAgo": "{n}m ago",
    "time.hoursAgo": "{n}h ago",
    "time.daysAgo": "{n}d ago",

    // Auth pages
    "auth.login.title": "Welcome Back!",
    "auth.login.subtitle": "Sign in to your account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.signIn": "Sign In",
    "auth.or": "or",
    "auth.signInGoogle": "Sign in with Google",
    "auth.noAccount": "Don't have an account?",
    "auth.signUp": "Sign up",
    "auth.register.title": "Create Your Account",
    "auth.register.subtitle": "Start generating professional security policies in minutes.",
    "auth.firstName": "First Name",
    "auth.lastName": "Last Name",
    "auth.confirmPassword": "Confirm Password",
    "auth.termsAgree": "By creating an account, you agree to our",
    "auth.termsOfService": "Terms of Service",
    "auth.and": "and",
    "auth.privacyPolicy": "Privacy Policy",
    "auth.createAccount": "Create Account",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.signInLink": "Sign in",
    "auth.checkEmail": "Check your email",
    "auth.confirmationSent": "We sent a confirmation link to {email}. Click it to activate your account.",
    "auth.backToSignIn": "Back to Sign In",
    "auth.passwordMismatch": "Passwords do not match.",
    "auth.passwordTooShort": "Password must be at least 8 characters.",
    "auth.reset.title": "Reset Password",
    "auth.reset.subtitleDefault": "Enter your email to receive a reset link.",
    "auth.reset.checkInbox": "Check your inbox.",
    "auth.reset.sentTo": "We sent a password reset link to {email}.",
    "auth.reset.resend": "Resend email",
    "auth.reset.sendLink": "Send Reset Link",

    // Error pages
    "notFound.title": "Page not found",
    "notFound.desc": "The page you're looking for doesn't exist or may have been moved.",
    "notFound.cta": "Back to home",
    "error.title": "Something went wrong",
    "error.desc": "An unexpected error occurred. Please try again — if it keeps happening, contact support.",
    "error.retry": "Try again",
    "error.cta": "Back to home",
  },

  fr: {
    // Navbar
    "nav.features": "Fonctionnalités",
    "nav.how": "Comment ça marche",
    "nav.pricing": "Tarification",
    "nav.login": "Connexion",
    "nav.start": "Commencer gratuitement",

    // Hero
    "hero.badge": "PLATEFORME CYBERSÉCURITÉ TOUT-EN-UN",
    "hero.tagline": "Scan. Secure. Comply.",
    "hero.title1": "La plateforme de cybersécurité",
    "hero.title2": "pour consultants IT",
    "hero.title3": "canadiens",
    "hero.subtitle": "Scannez la surface d'attaque de vos clients, générez leurs politiques de conformité, exportez des rapports professionnels — en 20 minutes par client.",
    "hero.cta": "Scanner mon domaine",
    "hero.demo": "Voir comment ça marche",
    "hero.badge1": "Loi 25 & PIPEDA",
    "hero.badge2": "MSP & Consultants IT",
    "hero.badge3": "NIST · CIS · ISO 27001",

    // Preview card
    "hero.preview.domain": "acme-corp.com",
    "hero.preview.score": "Score de risque",
    "hero.preview.risk": "Risque MOYEN",
    "hero.preview.finding1": "3 emails compromis détectés (HIBP)",
    "hero.preview.finding2": "SSL expire dans 12 jours",
    "hero.preview.finding3": "SPF & DMARC configurés",

    // Standards
    "standards.title": "Aligné avec les standards de l'industrie",

    // How it works
    "how.title": "Un flux complet en 4 étapes",
    "how.subtitle": "Du diagnostic à la livraison, tout est intégré.",
    "how.step1.title": "Diagnostic de surface d'attaque",
    "how.step1.desc": "Scan passif de votre domaine : SSL, DNS, emails compromis (HIBP), sous-domaines exposés.",
    "how.step2.title": "Score de sécurité + NIST/CIS/ISO",
    "how.step2.desc": "Score instantané avec mapping des contrôles de conformité et identification des écarts.",
    "how.step3.title": "Génération automatique de politiques",
    "how.step3.desc": "Politiques professionnelles générées par IA, adaptées aux vulnérabilités détectées.",
    "how.step4.title": "Export multi-format",
    "how.step4.desc": "PDF, Word, Confluence et Notion — prêts à livrer à vos clients ou auditeurs.",

    // Features
    "features.title": "Tout ce dont vous avez besoin",
    "features.subtitle": "Cybersécurité professionnelle, simplifiée pour les consultants et MSP.",
    "features.1.title": "Scan de domaine en temps réel",
    "features.1.desc": "SSL, DNS, HIBP, sous-domaines — analyse complète sans outil supplémentaire",
    "features.2.title": "Score de risque instantané",
    "features.2.desc": "Score 0–100 avec niveau FAIBLE/MOYEN/ÉLEVÉ et axes d'amélioration",
    "features.3.title": "5 types de politiques",
    "features.3.desc": "Mots de passe, Sauvegarde, Réponse aux incidents, Utilisation acceptable, Télétravail",
    "features.4.title": "Alignement NIST · CIS · ISO 27001",
    "features.4.desc": "Chaque politique mappée aux contrôles de conformité avec références précises",
    "features.5.title": "Export PDF + Word",
    "features.5.desc": "Documents professionnels avec logo, version, table des matières — prêts à livrer",
    "features.6.title": "Conforme Loi 25 & PIPEDA",
    "features.6.desc": "Politiques alignées avec les lois canadiennes sur la vie privée",

    // Pricing
    "pricing.title": "Tarification simple et transparente",
    "pricing.subtitle": "Sans frais cachés. Annulable en tout temps. Économisez ~17 % (2 mois gratuits) en facturation annuelle.",
    "pricing.subtitleBeta": "Nous sommes en bêta — toutes les fonctionnalités sont gratuites pendant qu'on bâtit ça avec nos premiers utilisateurs.",
    "pricing.annualNote": "Prix affichés mensuellement. Facturation annuelle disponible — 2 mois gratuits (~17 % de rabais).",
    "pricing.annualNoteBeta": "Les forfaits payants (Starter, Pro, Agence) arrivent bientôt — tout est gratuit pour les utilisateurs de la bêta en attendant.",
    "pricing.starter.name": "Starter",
    "pricing.starter.price": "59 $",
    "pricing.starter.period": "/mois",
    "pricing.starter.desc": "Pour les consultants solos avec un seul client.",
    "pricing.starter.cta": "Commencer",
    "pricing.starter.f1": "1 client",
    "pricing.starter.f2": "Diagnostic de surface d'attaque",
    "pricing.starter.f3": "Score de sécurité",
    "pricing.starter.f4": "Politiques générées par IA",
    "pricing.starter.f5": "Export PDF & Word",
    "pricing.pro.name": "Pro",
    "pricing.pro.badge": "Le plus populaire",
    "pricing.pro.price": "149 $",
    "pricing.pro.period": "/mois",
    "pricing.pro.desc": "Pour les consultants qui gèrent quelques clients.",
    "pricing.pro.cta": "Commencer",
    "pricing.pro.f1": "5 clients",
    "pricing.pro.f2": "Tout du plan Starter",
    "pricing.pro.f3": "Branding personnalisé sur les exports",
    "pricing.pro.f4": "Versionnement et régénération des politiques",
    "pricing.pro.f5": "Export Confluence & Notion",
    "pricing.agency.name": "Agence",
    "pricing.agency.price": "299 $",
    "pricing.agency.period": "/mois",
    "pricing.agency.desc": "Pour les agences et MSP qui gèrent tout un portefeuille de clients.",
    "pricing.agency.cta": "Commencer",
    "pricing.agency.f1": "Clients illimités",
    "pricing.agency.f2": "Tout du plan Pro",
    "pricing.agency.f3": "Portail client entièrement en marque blanche",
    "pricing.agency.f4": "Plusieurs membres d'équipe",
    "pricing.agency.f5": "Support prioritaire",
    "pricing.beta.name": "Beta",
    "pricing.beta.badge": "Temps limité",
    "pricing.beta.price": "Gratuit",
    "pricing.beta.period": "",
    "pricing.beta.desc": "Tout, gratuitement — en échange de feedback, d'appels et d'un témoignage.",
    "pricing.beta.cta": "Rejoindre la bêta",
    "pricing.beta.f1": "Clients illimités",
    "pricing.beta.f2": "Toutes les fonctionnalités débloquées",
    "pricing.beta.f3": "Ligne directe avec notre équipe",
    "pricing.beta.f4": "Influencez la feuille de route",
    "pricing.beta.f5": "Offre à durée limitée",

    // CTA
    "cta.title": "Démarrez votre premier diagnostic",
    "cta.subtitle": "Scannez votre domaine et obtenez vos premières politiques de conformité en moins de 20 minutes.",
    "cta.button": "Scanner mon domaine — Gratuit",

    // Footer
    "footer.copy": "© 2026 SecurePilot. Conçu pour les consultants IT et MSP canadiens.",

    // Dashboard nav
    "dash.nav.dashboard": "Tableau de bord",
    "dash.nav.scan": "Diagnostic",
    "dash.nav.policies": "Politiques",
    "dash.nav.generate": "Générer une politique",
    "dash.nav.clients": "Clients",
    "dash.nav.securityScore": "Score de sécurité",
    "dash.nav.auditEvidence": "Preuves d'audit",
    "dash.nav.frameworks": "Référentiels",
    "dash.nav.settings": "Paramètres",
    "dash.nav.logout": "Déconnexion",

    // Topbar / client switcher
    "dash.topbar.notifications": "Notifications",
    "dash.topbar.markAllRead": "Tout marquer lu",
    "dash.topbar.caughtUp": "Vous êtes à jour.",
    "dash.client.select": "Choisir un client",
    "dash.client.manage": "Gérer les clients",

    // Clients list
    "clients.title": "Clients",
    "clients.limitUnlimited": "Clients illimités avec votre forfait.",
    "clients.limitUsed.one": "{count} / {limit} client utilisé sur votre forfait {plan}.",
    "clients.limitUsed.other": "{count} / {limit} clients utilisés sur votre forfait {plan}.",
    "clients.add": "Ajouter un client",
    "clients.limitReached": "Vous avez atteint la limite de clients de votre forfait.",
    "clients.upgrade": "Améliorez votre forfait",
    "clients.toAddMore": "pour ajouter plus de clients.",
    "clients.namePlaceholder": "Nom du client ou de l'entreprise",
    "clients.create": "Créer",
    "clients.empty": "Aucun client pour l'instant. Ajoutez le premier pour commencer.",
    "clients.added": "Ajouté le {date}",
    "clients.createFailed": "Échec de la création du client.",
    "clients.created": "Client créé.",
    "clients.deleteConfirm": "Supprimer ce client ainsi que toutes ses politiques, scans et registres? Cette action est irréversible.",
    "clients.deleteFailed": "Échec de la suppression du client.",
    "clients.deleted": "Client supprimé.",
    "clients.genericError": "Une erreur est survenue.",

    // Client profile
    "clientProfile.back": "Retour aux clients",
    "clientProfile.subtitle": "Profil d'entreprise et de sécurité utilisé pour générer les politiques de ce client.",
    "clientProfile.tab.company": "Informations sur l'entreprise",
    "clientProfile.tab.security": "Informations de sécurité",
    "clientProfile.companyName": "Nom de l'entreprise",
    "clientProfile.website": "Site web (optionnel)",
    "clientProfile.industry": "Industrie",
    "clientProfile.selectIndustry": "Sélectionner l'industrie",
    "clientProfile.employeeCount": "Nombre d'employés",
    "clientProfile.selectRange": "Sélectionner une plage",
    "clientProfile.phone": "Téléphone",
    "clientProfile.email": "Courriel",
    "clientProfile.country": "Pays",
    "clientProfile.province": "Province / État",
    "clientProfile.cloudServices": "Services infonuagiques",
    "clientProfile.remoteWork": "Télétravail",
    "clientProfile.microsoft365": "Microsoft 365",
    "clientProfile.googleWorkspace": "Google Workspace",
    "clientProfile.mfaEnabled": "MFA activée",
    "clientProfile.hasBackups": "Sauvegardes en place",
    "clientProfile.hasItDept": "Département TI / MSP externe",
    "clientProfile.personalDevices": "Les employés utilisent des appareils personnels",
    "clientProfile.save": "Enregistrer les modifications",
    "clientProfile.saveFailed": "Échec de l'enregistrement du profil.",
    "clientProfile.saved": "Profil enregistré!",
    "clientProfile.industry.accounting": "Comptabilité",
    "clientProfile.industry.construction": "Construction",
    "clientProfile.industry.consulting": "Consultation",
    "clientProfile.industry.education": "Éducation",
    "clientProfile.industry.finance": "Finance",
    "clientProfile.industry.healthcare": "Santé",
    "clientProfile.industry.hospitality": "Hôtellerie",
    "clientProfile.industry.itWeb": "TI / Agence web",
    "clientProfile.industry.legal": "Juridique",
    "clientProfile.industry.manufacturing": "Manufacturier",
    "clientProfile.industry.realEstate": "Immobilier",
    "clientProfile.industry.retail": "Commerce de détail",
    "clientProfile.industry.other": "Autre",
    "clientProfile.cloud.none": "Aucun",
    "clientProfile.cloud.mixed": "Mixte / Plusieurs",
    "clientProfile.country.canada": "Canada",
    "clientProfile.country.us": "États-Unis",

    // Choose plan
    "plan.changeTitle": "Changer de forfait",
    "plan.chooseTitle": "Choisissez votre forfait",
    "plan.changeSubtitle": "Changez de forfait à tout moment — les changements s'appliquent immédiatement.",
    "plan.chooseSubtitle": "Choisissez un forfait pour déverrouiller votre tableau de bord. Vous pouvez le changer à tout moment.",
    "plan.monthly": "Mensuel",
    "plan.annual": "Annuel",
    "plan.twoMonthsFree": "2 mois gratuits",
    "plan.perMonth": "/mois",
    "plan.free": "Gratuit",
    "plan.billedPerYear": "Facturé {amount} $/an",
    "plan.mostPopular": "LE PLUS POPULAIRE",
    "plan.limitedTime": "TEMPS LIMITÉ",
    "plan.unlimitedClients": "Clients illimités",
    "plan.clientCount.one": "{count} client",
    "plan.clientCount.other": "{count} clients",
    "plan.current": "Forfait actuel",
    "plan.saving": "Enregistrement…",
    "plan.joinBeta": "Rejoindre la bêta",
    "plan.choose": "Choisir {name}",
    "plan.selectFailed": "Échec de la sélection du forfait.",
    "plan.onPlan": "Vous êtes sur le forfait {name}.",
    "plan.checkoutFailed": "Échec du démarrage du paiement.",
    "plan.genericError": "Une erreur est survenue.",
    "plan.tagline.starter": "Pour les consultants solos avec un seul client.",
    "plan.tagline.pro": "Pour les consultants qui gèrent quelques clients.",
    "plan.tagline.agency": "Pour les agences et MSP qui gèrent tout un portefeuille de clients.",
    "plan.tagline.beta": "Tout, gratuitement — en échange de feedback, d'appels et d'un témoignage.",
    "plan.include.scan": "Diagnostic de surface d'attaque",
    "plan.include.score": "Score de sécurité",
    "plan.include.aiPolicies": "Politiques générées par IA",
    "plan.include.export": "Export PDF & Word",
    "plan.feature.branding": "Branding personnalisé sur les exports",
    "plan.feature.versioning": "Versionnement et régénération des politiques",
    "plan.feature.confluence_notion": "Export Confluence & Notion",
    "plan.feature.white_label": "Portail client entièrement en marque blanche",
    "plan.feature.multi_user": "Plusieurs membres d'équipe",
    "plan.feature.priority_support": "Support prioritaire",

    // Dashboard
    "dashboard.scanBanner.title": "Diagnostic de sécurité",
    "dashboard.scanBanner.subtitle": "Analysez la surface d'attaque de votre domaine en 30 secondes.",
    "dashboard.scanBanner.cta": "Lancer le scan",
    "dashboard.greeting": "Bonjour, {name}! 👋",
    "dashboard.subtitle": "Voici un aperçu de votre sécurité.",
    "dashboard.generateNew": "Générer une nouvelle politique",
    "dashboard.policiesGenerated": "Politiques générées",
    "dashboard.viewAllPolicies": "Voir toutes les politiques →",
    "dashboard.securityScore": "Score de sécurité",
    "dashboard.viewDetails": "Voir les détails →",
    "dashboard.recommendations": "Recommandations",
    "dashboard.viewRecommendations": "Voir les recommandations →",
    "dashboard.recentPolicies": "Politiques récentes",
    "dashboard.viewAll": "Voir tout",
    "dashboard.noPolicies": "Aucune politique pour l'instant. Générez la première!",
    "dashboard.generatePolicy": "Générer une politique",
    "dashboard.versionDate": "Version {version} · {date}",
    "dashboard.topRecommendations": "Meilleures recommandations",
    "dashboard.noRecommendations": "Générez une politique pour voir des recommandations.",
    "dashboard.viewAllRecommendations": "Voir toutes les recommandations →",
    "dashboard.needsReview.one": "{count} politique nécessite une révision",
    "dashboard.needsReview.other": "{count} politiques nécessitent une révision",
    "dashboard.frameworkUpdated": "Un référentiel auquel vous êtes aligné a été mis à jour depuis la génération. Révisez les politiques concernées.",
    "dashboard.reviewNow": "Réviser maintenant →",
    "dashboard.completeProfile": "Complétez votre profil d'entreprise",
    "dashboard.completeProfileDesc": "Ajoutez les détails de votre entreprise pour des politiques plus précises et personnalisées.",
    "dashboard.setUpProfile": "Configurer le profil →",

    // Policies list
    "policiesPage.title": "Politiques",
    "policiesPage.subtitle": "Gérez et consultez vos politiques de sécurité.",
    "policiesPage.generateNew": "Générer une nouvelle politique",
    "policiesList.search": "Rechercher des politiques…",
    "policiesList.name": "Nom de la politique",
    "policiesList.status": "Statut",
    "policiesList.lastUpdated": "Dernière mise à jour",
    "policiesList.actions": "Actions",
    "policiesList.noMatch": "Aucune politique ne correspond à votre recherche.",
    "policiesList.none": "Aucune politique pour l'instant.",
    "policiesList.version": "Version {version}",
    "policiesList.rename": "Renommer",
    "policiesList.delete": "Supprimer",
    "policiesList.save": "Enregistrer",
    "policiesList.cancel": "Annuler",
    "policiesList.deleteConfirm": "Supprimer cette politique? Cette action est irréversible.",
    "policiesList.deleteFailed": "Échec de la suppression.",
    "policiesList.deleted": "Politique supprimée.",
    "policiesList.renameFailed": "Échec du renommage.",
    "policiesList.renamed": "Renommé.",

    // Scan
    "scan.stage1": "Vérification SSL…",
    "scan.stage2": "Analyse des fuites…",
    "scan.stage3": "Scan DNS…",
    "scan.stage4": "Génération du rapport…",
    "scan.invalidDomain": "Entrez un domaine valide (ex. entreprise.com).",
    "scan.failed": "Le diagnostic a échoué.",
    "scan.genericError": "Quelque chose s'est mal passé.",
    "scan.scanningTitle": "Diagnostic en cours…",
    "scan.scanningNote": "Ça peut prendre jusqu'à 30 secondes.",
    "scan.title": "Diagnostic de surface d'attaque",
    "scan.subtitle": "Analysez la surface d'attaque de votre domaine : certificat SSL, fuites de données, configuration DNS et sous-domaines exposés.",
    "scan.domainLabel": "Domaine à analyser",
    "scan.domainPlaceholder": "entreprise.com",
    "scan.launch": "Lancer le diagnostic",
    "scan.report.scannedOn": "Diagnostiqué le {date}",
    "scan.report.newScan": "Nouveau scan",
    "scan.report.ssl": "SSL",
    "scan.report.grade": "Grade : {grade}",
    "scan.report.certExpired": "Certificat expiré",
    "scan.report.expiresIn": "Expire dans {days} jours",
    "scan.report.expiryUnknown": "Expiration inconnue",
    "scan.report.noSSL": "Aucun certificat SSL détecté",
    "scan.report.dataLeaks": "Fuites de données",
    "scan.report.compromisedAccounts.one": "{count} compte compromis",
    "scan.report.compromisedAccounts.other": "{count} comptes compromis",
    "scan.report.dns": "DNS",
    "scan.report.subdomains": "Sous-domaines",
    "scan.report.subdomainsExposed.one": "{count} sous-domaine exposé",
    "scan.report.subdomainsExposed.other": "{count} sous-domaines exposés",
    "scan.report.findings": "Constats du diagnostic",
    "scan.report.recommendedPolicies": "Politiques recommandées",
    "scan.report.basedOn": "Basées sur les vulnérabilités détectées lors du diagnostic.",
    "scan.report.urgent": "Urgent",
    "scan.report.generate": "Générer",
    "scan.risk.low": "Risque FAIBLE",
    "scan.risk.medium": "Risque MOYEN",
    "scan.risk.high": "Risque ÉLEVÉ",
    "scan.policy.password.label": "Politique de mots de passe",
    "scan.policy.password.desc": "Exigences de complexité, expiration et gestion des mots de passe.",
    "scan.policy.incidentResponse.label": "Plan de réponse aux incidents",
    "scan.policy.incidentResponse.desc": "Procédure à suivre en cas d'incident de sécurité.",
    "scan.policy.backup.label": "Politique de sauvegarde",
    "scan.policy.backup.desc": "Fréquence, emplacement et tests de restauration des sauvegardes.",
    "scan.policy.acceptableUse.label": "Politique d'utilisation acceptable",
    "scan.policy.acceptableUse.desc": "Règles d'usage des ressources technologiques de l'entreprise.",
    "scan.policy.remoteWork.label": "Politique de télétravail",
    "scan.policy.remoteWork.desc": "Sécurisation de l'accès distant et des appareils hors bureau.",

    // Audit evidence — page & PDF
    "audit.pageTitle": "Preuves d'audit",
    "audit.pageSubtitle": "Maintenez les registres demandés par les auditeurs et assureurs cyber, et exportez un dossier d'audit complet pour {companyName}.",
    "audit.generating": "Génération…",
    "audit.generateFullReport": "Générer le rapport d'audit complet",
    "audit.reportFailed": "Échec de la génération du rapport d'audit. Veuillez réessayer.",
    "audit.pdf.title": "Dossier d'audit de sécurité",
    "audit.pdf.generatedOn": "Généré le {date}",
    "audit.pdf.companyProfile": "1. Profil de l'entreprise",
    "audit.pdf.industry": "Industrie",
    "audit.pdf.employees": "Employés",
    "audit.pdf.countryProvince": "Pays / Province",
    "audit.pdf.mfaEnabled": "MFA activée",
    "audit.pdf.backupsInPlace": "Sauvegardes en place",
    "audit.pdf.itDeptMsp": "Département TI / MSP",
    "audit.pdf.activePolicies": "2. Politiques de sécurité actives",
    "audit.pdf.policy": "Politique",
    "audit.pdf.version": "Version",
    "audit.pdf.status": "Statut",
    "audit.pdf.securityScore": "Score de sécurité",
    "audit.pdf.lastUpdated": "Dernière mise à jour",
    "audit.pdf.yes": "Oui",
    "audit.pdf.no": "Non",
    "audit.pdf.footer": "{companyName} — Dossier d'audit de sécurité — CONFIDENTIEL",

    // Audit registers
    "register.unsavedChanges": "Modifications non enregistrées",
    "register.addRow": "Ajouter une ligne",
    "register.save": "Enregistrer",
    "register.saving": "Enregistrement…",
    "register.saved": "{title} enregistré.",
    "register.saveFailed": "Échec de l'enregistrement. Veuillez réessayer.",
    "register.empty": "Aucune entrée pour l'instant. Cliquez sur « Ajouter une ligne » pour commencer ce registre.",
    "register.exportPDF": "Exporter en PDF",
    "register.pdfFooter": "{companyName} — Généré le {date} — Confidentiel",
    "register.pdfFailed": "Échec de la génération du PDF. Veuillez réessayer.",

    "artifact.title.backup_register": "Registre de sauvegarde",
    "artifact.desc.backup_register": "Preuve des données sauvegardées, leur fréquence et leur emplacement — exigée par la plupart des auditeurs et assureurs cyber.",
    "artifact.title.asset_inventory": "Inventaire des actifs",
    "artifact.desc.asset_inventory": "Registre du matériel, des logiciels et des actifs infonuagiques qui stockent ou traitent les données de l'entreprise.",
    "artifact.title.training_register": "Registre de formation à la sécurité",
    "artifact.desc.training_register": "Preuve que les employés ont complété une formation de sensibilisation à la sécurité — souvent demandée lors des audits.",
    "artifact.title.incident_register": "Registre des incidents",
    "artifact.desc.incident_register": "Journal des incidents de sécurité, leur gravité et leur résolution — exigé par la plupart des obligations de réponse aux incidents et de notification des atteintes.",
    "artifact.title.access_register": "Registre des accès",
    "artifact.desc.access_register": "Registre de qui a accès à quels systèmes et pourquoi — preuve que les accès sont accordés, révisés et révoqués de façon délibérée.",
    "artifact.title.rights_request_register": "Registre des demandes de droits des personnes concernées",
    "artifact.desc.rights_request_register": "Journal des demandes d'accès, de rectification, d'effacement et de portabilité — preuve de conformité aux obligations de la Loi 25 / RGPD sur les droits des personnes concernées.",
    "artifact.title.third_party_register": "Registre des tiers / fournisseurs",
    "artifact.desc.third_party_register": "Inventaire des fournisseurs et prestataires de services qui accèdent ou traitent les données de l'entreprise, et leurs garanties contractuelles.",

    "artifact.col.systemData": "Système / Données",
    "artifact.col.frequency": "Fréquence",
    "artifact.col.storageLocation": "Emplacement de stockage",
    "artifact.col.retentionPeriod": "Période de rétention",
    "artifact.col.encrypted": "Chiffré",
    "artifact.col.lastRestoreTest": "Dernier test de restauration",
    "artifact.col.assetName": "Nom de l'actif",
    "artifact.col.category": "Catégorie",
    "artifact.col.owner": "Propriétaire",
    "artifact.col.criticality": "Criticité",
    "artifact.col.notes": "Notes",
    "artifact.col.employee": "Employé",
    "artifact.col.trainingTopic": "Formation / Sujet",
    "artifact.col.completedOn": "Complétée le",
    "artifact.col.nextDue": "Prochaine échéance",
    "artifact.col.date": "Date",
    "artifact.col.description": "Description",
    "artifact.col.severity": "Gravité",
    "artifact.col.affectedSystems": "Systèmes touchés",
    "artifact.col.reportedBy": "Signalé par",
    "artifact.col.status": "Statut",
    "artifact.col.resolutionDate": "Date de résolution",
    "artifact.col.employeeUser": "Employé / Utilisateur",
    "artifact.col.systemResource": "Système / Ressource",
    "artifact.col.accessLevel": "Niveau d'accès",
    "artifact.col.grantedDate": "Date d'octroi",
    "artifact.col.grantedBy": "Octroyé par",
    "artifact.col.lastReviewed": "Dernière révision",
    "artifact.col.revokedDate": "Date de révocation",
    "artifact.col.dateReceived": "Date de réception",
    "artifact.col.requester": "Demandeur",
    "artifact.col.requestType": "Type de demande",
    "artifact.col.responseDate": "Date de réponse",
    "artifact.col.vendorName": "Nom du fournisseur",
    "artifact.col.serviceProvided": "Service fourni",
    "artifact.col.dataAccessLevel": "Niveau d'accès aux données",
    "artifact.col.contractDate": "Date du contrat",
    "artifact.col.dpaSigned": "Entente DPA signée",

    "artifact.opt.realTime": "Temps réel",
    "artifact.opt.daily": "Quotidien",
    "artifact.opt.weekly": "Hebdomadaire",
    "artifact.opt.monthly": "Mensuel",
    "artifact.opt.yes": "Oui",
    "artifact.opt.no": "Non",
    "artifact.opt.hardware": "Matériel",
    "artifact.opt.software": "Logiciel",
    "artifact.opt.cloudService": "Service infonuagique",
    "artifact.opt.data": "Données",
    "artifact.opt.low": "Faible",
    "artifact.opt.medium": "Moyen",
    "artifact.opt.high": "Élevé",
    "artifact.opt.critical": "Critique",
    "artifact.opt.open": "Ouvert",
    "artifact.opt.inProgress": "En cours",
    "artifact.opt.resolved": "Résolu",
    "artifact.opt.completed": "Complété",
    "artifact.opt.denied": "Refusé",
    "artifact.opt.access": "Accès",
    "artifact.opt.rectification": "Rectification",
    "artifact.opt.erasure": "Effacement",
    "artifact.opt.portability": "Portabilité",
    "artifact.opt.objection": "Objection",
    "artifact.opt.none": "Aucun",
    "artifact.opt.limited": "Limité",
    "artifact.opt.full": "Complet",

    // Policy detail page
    "policyDetail.regenerate": "Régénérer",
    "policyDetail.regeneratePro": "Régénérer (Pro)",
    "policyDetail.docInfo": "Informations du document",
    "policyDetail.policyOwner": "Responsable de la politique",
    "policyDetail.itDepartment": "Département TI",
    "policyDetail.reviewDate": "Date de révision",
    "policyDetail.nextReview": "Prochaine révision",
    "policyDetail.in12Months": "Dans 12 mois",
    "policyDetail.version": "Version",
    "policyDetail.outOf100": "sur 100",
    "policyDetail.viewFullReport": "Voir le rapport de sécurité complet →",
    "tabs.document": "Document",
    "tabs.versionHistory": "Historique des versions",
    "sidebar.auditEvidence.desc": "Registres à maintenir pour prouver la conformité à cette politique.",
    "sidebar.auditEvidence.manage": "Gérer les registres →",
    "sidebar.bestPractices.title": "Bonnes pratiques",
    "sidebar.bestPractices.dos": "✅ À faire",
    "sidebar.bestPractices.donts": "❌ À éviter",
    "sidebar.actionChecklist.title": "Actions prioritaires",
    "sidebar.actionChecklist.completed": "{done}/{total} complétées",
    "sidebar.actionChecklist.priority.high": "Haute",
    "sidebar.actionChecklist.priority.medium": "Moyenne",
    "sidebar.actionChecklist.priority.low": "Faible",
    "complianceBadges.alignedWith": "Aligné avec :",
    "sidebar.policyImportance.title": "Pourquoi cette politique est importante",
    "sidebar.policyImportance.oftenRequired": "Souvent exigée par",
    "sidebar.clientPortal.title": "Portail client",
    "sidebar.clientPortal.desc": "Partagez un lien en lecture seule pour que votre client puisse voir cette politique sans compte.",
    "sidebar.clientPortal.linkEnabled": "Lien activé",
    "sidebar.clientPortal.linkDisabled": "Lien désactivé",
    "sidebar.clientPortal.copyLink": "Copier le lien",
    "sidebar.clientPortal.enabled": "Lien du portail client activé.",
    "sidebar.clientPortal.disabled": "Lien du portail client désactivé.",
    "sidebar.clientPortal.updateFailed": "Échec de la mise à jour du lien du portail client.",
    "exportWorkspace.exporting": "Exportation…",
    "exportWorkspace.exportTo": "Exporter vers {provider}",
    "exportWorkspace.exportFailed": "Échec de l'export vers {provider}.",
    "exportWorkspace.exported": "Exporté vers {provider}.",
    "exportWorkspace.openPage": "Ouvrir la page",
    "exportWorkspace.genericError": "Une erreur est survenue.",
    "versionHistory.backToList": "Retour à la liste des versions",
    "versionHistory.restoreThis": "Restaurer cette version",
    "versionHistory.restoring": "Restauration…",
    "versionHistory.restoreFailed": "Échec de la restauration",
    "versionHistory.restored": "Restauré à v{version}.0",
    "versionHistory.genericError": "Une erreur est survenue.",
    "versionHistory.current": "Actuelle",
    "versionHistory.change.generated": "Générée",
    "versionHistory.change.regenerated": "Régénérée",
    "versionHistory.change.restored": "Restaurée",

    // Security score page
    "securityScore.subtitle.one": "Basé sur {count} politique générée.",
    "securityScore.subtitle.other": "Basé sur {count} politiques générées.",
    "securityScore.noScoreTitle": "Aucun score de sécurité pour l'instant",
    "securityScore.noScoreDesc": "Générez votre première politique de sécurité et nous calculerons automatiquement votre score de sécurité avec forces, faiblesses et recommandations.",
    "securityScore.generateFirst": "Générer la première politique",
    "securityScore.execSummary": "Résumé exécutif",
    "securityScore.maturityLevel": "Niveau de maturité",
    "securityScore.strengths": "Forces",
    "securityScore.weaknesses": "Faiblesses",
    "securityScore.scoreHistory": "Historique du score",
    "securityScore.scoreHistoryDesc": "Évolution du score de sécurité de chaque politique au fil des régénérations.",
    "securityScore.overVersions": "sur {count} versions",
    "securityScore.actionPlan": "Plan d'action prioritaire",
    "securityScore.gapAnalysis": "Analyse des écarts",
    "securityScore.gapAnalysisDesc": "Basée sur votre politique générée le plus récemment.",
    "securityScore.currentCompliance": "Conformité actuelle",
    "securityScore.missingControls": "Contrôles manquants",
    "securityScore.associatedRisk": "Risque associé",
    "securityScore.recommendations": "Recommandations prioritaires",
    "securityScore.missingPolicies": "Politiques manquantes",
    "securityScore.generateMissing": "Générer les politiques manquantes",
    "securityScore.ring.good": "Bon",
    "securityScore.ring.fair": "Moyen",
    "securityScore.ring.poor": "Faible",
    "securityScore.priority.high": "Priorité haute",
    "securityScore.priority.medium": "Priorité moyenne",
    "securityScore.priority.low": "Priorité faible",
    "securityScore.maturity.basic": "Basique",
    "securityScore.maturity.developing": "En développement",
    "securityScore.maturity.defined": "Défini",
    "securityScore.maturity.advanced": "Avancé",

    // Frameworks page
    "frameworks.title": "Tableau de bord des référentiels",
    "frameworks.subtitle": "Couverture de conformité pour chaque référentiel auquel vos politiques sont alignées.",
    "frameworks.outdatedBadge": "Périmé",
    "frameworks.policyCount.one": "{count} politique",
    "frameworks.policyCount.other": "{count} politiques",
    "frameworks.affectedNotice.one": "{count} politique référence une révision de référentiel périmée",
    "frameworks.affectedNotice.other": "{count} politiques référencent une révision de référentiel périmée",
    "frameworks.affectedDesc": "Un référentiel auquel vous êtes aligné a été mis à jour depuis la génération de votre politique. Régénérez les politiques concernées ci-dessous pour les mettre à jour.",
    "frameworks.currentVersion": "Version actuelle : {version}",
    "frameworks.relevantFor": "Pertinent pour",
    "frameworks.relatedPolicies": "Politiques associées",
    "frameworks.affectedListIntro": "{count} de vos politiques référencent une ancienne révision :",
    "frameworks.update": "Mettre à jour",
    "frameworks.effort": "Effort",
    "frameworks.effort.high": "Élevé",
    "frameworks.effort.medium": "Moyen",
    "frameworks.effort.lowMedium": "Faible à moyen",
    "frameworks.footerTitle": "SecurePilot aligne automatiquement vos politiques",
    "frameworks.footerDesc": "Chaque politique générée est automatiquement mappée aux référentiels applicables (NIST, CIS, ISO 27001, SOC 2, Loi 25, RGPD) selon le contexte de votre entreprise, et signalée ici si le standard sous-jacent est mis à jour.",

    "fw.iso27001.tagline": "Système de gestion de la sécurité de l'information",
    "fw.iso27001.desc": "Norme internationale définissant les exigences pour établir, mettre en œuvre, maintenir et améliorer un système de gestion de la sécurité de l'information (SGSI). Reconnue mondialement et souvent exigée dans les appels d'offres et processus d'approvisionnement d'entreprise.",
    "fw.iso27001.relevant1": "Certification formelle",
    "fw.iso27001.relevant2": "Clients entreprise",
    "fw.iso27001.relevant3": "Approvisionnement gouvernemental",
    "fw.iso27001.policy1": "Politique de mots de passe",
    "fw.iso27001.policy2": "Contrôle d'accès",
    "fw.iso27001.policy3": "Réponse aux incidents",
    "fw.iso27001.policy4": "Continuité des activités",

    "fw.nist.tagline": "Cadre de cybersécurité du National Institute of Standards and Technology",
    "fw.nist.desc": "Cadre volontaire américain organisé autour de 5 fonctions : Identifier, Protéger, Détecter, Répondre, Récupérer. Largement adopté en Amérique du Nord, particulièrement par les PME qui veulent structurer leur posture de sécurité sans viser une certification formelle.",
    "fw.nist.relevant1": "PME nord-américaines",
    "fw.nist.relevant2": "Secteur financier",
    "fw.nist.relevant3": "Infrastructures critiques",
    "fw.nist.policy1": "Politique de sauvegarde",
    "fw.nist.policy2": "Plan de réponse aux incidents",
    "fw.nist.policy3": "Gestion des accès",

    "fw.cis.tagline": "Center for Internet Security — 18 contrôles prioritaires",
    "fw.cis.desc": "18 contrôles concrets et priorisés pour réduire le risque cyber. Idéal pour les PME qui débutent : commencez par les contrôles du groupe de mise en œuvre 1 (IG1) pour couvrir 85 % des attaques courantes avec un effort et des ressources minimaux.",
    "fw.cis.relevant1": "PME qui débutent",
    "fw.cis.relevant2": "Gains rapides en sécurité",
    "fw.cis.relevant3": "Ressources TI limitées",
    "fw.cis.policy1": "Inventaire des actifs",
    "fw.cis.policy2": "Configuration sécurisée",
    "fw.cis.policy3": "Contrôle des accès privilégiés",

    "fw.soc2.tagline": "Service Organization Control — Confiance, Sécurité, Disponibilité",
    "fw.soc2.desc": "Rapport d'audit basé sur 5 critères de service de confiance : Sécurité, Disponibilité, Intégrité du traitement, Confidentialité et Vie privée. Fortement demandé par les clients SaaS et les entreprises technologiques pour démontrer leur rigueur opérationnelle.",
    "fw.soc2.relevant1": "Entreprises SaaS",
    "fw.soc2.relevant2": "Fournisseurs infonuagiques",
    "fw.soc2.relevant3": "Clients entreprise américains",
    "fw.soc2.policy1": "Contrôle d'accès logique",
    "fw.soc2.policy2": "Surveillance continue",
    "fw.soc2.policy3": "Gestion des changements",

    "fw.loi25.tagline": "Loi modernisant des dispositions législatives en matière de protection des renseignements personnels (Québec)",
    "fw.loi25.desc": "Loi québécoise en vigueur depuis 2022 qui renforce la protection des renseignements personnels. Elle exige la désignation d'un responsable de la protection des renseignements personnels, des évaluations des facteurs relatifs à la vie privée (EFVP), et la notification des incidents dans les 72 heures.",
    "fw.loi25.relevant1": "Entreprises basées au Québec",
    "fw.loi25.relevant2": "Toute organisation collectant des données au Québec",
    "fw.loi25.policy1": "Politique de confidentialité",
    "fw.loi25.policy2": "Plan de réponse aux incidents",
    "fw.loi25.policy3": "Politique BYOD",

    "fw.rgpd.tagline": "Règlement général sur la protection des données (Europe)",
    "fw.rgpd.desc": "Règlement européen applicable à toute organisation traitant des données personnelles de résidents de l'UE. Exige le consentement, la minimisation des données, des mesures de sécurité appropriées et la notification des atteintes dans les 72 heures.",
    "fw.rgpd.relevant1": "Clients européens",
    "fw.rgpd.relevant2": "Commerce international",
    "fw.rgpd.relevant3": "Organisations avec opérations dans l'UE",
    "fw.rgpd.policy1": "Politique de confidentialité",
    "fw.rgpd.policy2": "Politique de rétention des données",
    "fw.rgpd.policy3": "Plan de réponse aux incidents",

    // Generate policy page
    "generate.loadingPolicy": "Chargement de la politique…",
    "generate.generatingTitle": "Génération de votre politique…",
    "generate.generatingDesc": "Notre IA rédige une politique {type} professionnelle adaptée à votre entreprise.",
    "generate.generatingTime": "Cela prend généralement 15 à 30 secondes",
    "generate.scanBanner": "Ce type de politique a été recommandé suite au diagnostic de votre domaine.",
    "generate.why.title": "Pourquoi générez-vous cette politique?",
    "generate.why.subtitle": "Cela aide notre IA à adapter le ton et les sections à votre contexte spécifique.",
    "generate.back": "Retour",
    "generate.continue": "Continuer",
    "generate.stepOf": "Étape {current} sur {total}",
    "generate.answerPlaceholder": "Tapez votre réponse…",
    "generate.next": "Suivant",
    "generate.regenerate": "Régénérer",
    "generate.generate": "Générer",
    "generate.pageTitle": "Générer une politique",
    "generate.pageSubtitle": "Choisissez le type de politique à générer.",
    "generate.policyNotFound": "Politique introuvable.",
    "generate.generationFailed": "Échec de la génération",
    "generate.genericError": "Une erreur est survenue.",
    "generate.policy.password.desc": "Créez une politique de mots de passe robuste pour votre équipe.",
    "generate.policy.backup.desc": "Définissez vos règles de sauvegarde et objectifs de récupération.",
    "generate.policy.incidentResponse.desc": "Préparez votre équipe aux incidents de sécurité.",
    "generate.policy.acceptableUse.desc": "Établissez les règles d'utilisation acceptable de la technologie.",
    "generate.policy.remoteWork.desc": "Sécurisez efficacement votre main-d'œuvre à distance.",
    "genReason.audit": "Audit interne ou externe",
    "genReason.insurance": "Exigence d'assurance cyber",
    "genReason.client": "Exigence d'un client ou partenaire",
    "genReason.certification": "Certification (ISO 27001, SOC 2…)",
    "genReason.internal": "Amélioration interne",

    // Shared (client portal) policy page
    "shared.readOnly": "Portail client en lecture seule",
    "shared.execSummary": "Résumé exécutif",
    "shared.footer": "Ceci est une vue partagée en lecture seule générée avec SecurePilot.",

    // Settings page
    "settings.title": "Paramètres",
    "settings.subtitle": "Gérez les paramètres et préférences de votre compte.",
    "settings.tab.profile": "Profil",
    "settings.tab.plan": "Forfait et facturation",
    "settings.tab.branding": "Image de marque",
    "settings.tab.notifications": "Notifications",
    "settings.tab.password": "Mot de passe",
    "settings.tab.integrations": "Intégrations",
    "settings.tab.danger": "Zone de danger",
    "settings.upsell.proFeature": "{feature} est une fonctionnalité Pro",
    "settings.upsell.upgrade": "Améliorez votre forfait pour déverrouiller ceci.",
    "settings.upsell.viewPlans": "Voir les forfaits",
    "settings.profile.title": "Informations du profil",
    "settings.profile.fullName": "Nom complet",
    "settings.profile.lastName": "Nom de famille",
    "settings.profile.email": "Courriel",
    "settings.profile.emailHint": "Le courriel ne peut pas être modifié ici. Contactez le support.",
    "settings.saveChanges": "Enregistrer les modifications",
    "settings.profile.updated": "Profil mis à jour!",
    "settings.plan.title": "Forfait et facturation",
    "settings.plan.name": "Forfait {name}",
    "settings.plan.free": "Gratuit",
    "settings.plan.perYear": "{amount} $/an",
    "settings.plan.perMonth": "{amount} $/mois",
    "settings.plan.change": "Changer de forfait",
    "settings.plan.includedFeatures": "Fonctionnalités incluses",
    "settings.plan.coreOnly": "Fonctionnalités de base seulement — améliorez votre forfait pour en débloquer plus.",
    "settings.plan.loading": "Chargement de votre forfait…",
    "settings.branding.title": "Image de marque",
    "settings.branding.desc": "Personnalisez vos politiques exportées avec l'image de marque de votre agence au lieu de celle de SecurePilot. S'applique à tous les clients.",
    "settings.branding.name": "Nom de la marque",
    "settings.branding.nameHint": "Affiché sur les pages de couverture PDF et Word au lieu de l'image de marque par défaut de SecurePilot.",
    "settings.branding.color": "Couleur principale",
    "settings.branding.logoUrl": "URL du logo (optionnel)",
    "settings.branding.logoHint": "Une URL d'image hébergée — les logos carrés fonctionnent mieux.",
    "settings.branding.logoPreviewAlt": "Aperçu du logo de la marque",
    "settings.branding.save": "Enregistrer l'image de marque",
    "settings.branding.saveFailed": "Échec de l'enregistrement de l'image de marque. Votre forfait ne l'inclut peut-être pas.",
    "settings.branding.saved": "Image de marque enregistrée.",
    "settings.notifications.title": "Notifications",
    "settings.notifications.reviewReminders": "Rappels de révision des politiques",
    "settings.notifications.reviewRemindersDesc": "Soyez notifié quand une politique doit être révisée",
    "settings.notifications.scoreUpdates": "Mises à jour du score de sécurité",
    "settings.notifications.scoreUpdatesDesc": "Soyez notifié quand votre score de sécurité change",
    "settings.notifications.newRecs": "Nouvelles recommandations",
    "settings.notifications.newRecsDesc": "Soyez notifié quand de nouvelles recommandations sont disponibles",
    "settings.notifications.savePrefs": "Enregistrer les préférences",
    "settings.password.title": "Changer le mot de passe",
    "settings.password.current": "Mot de passe actuel",
    "settings.password.new": "Nouveau mot de passe",
    "settings.password.confirm": "Confirmer le nouveau mot de passe",
    "settings.password.update": "Mettre à jour le mot de passe",
    "settings.password.mismatch": "Les mots de passe ne correspondent pas.",
    "settings.password.tooShort": "Le mot de passe doit contenir au moins 8 caractères.",
    "settings.password.updated": "Mot de passe mis à jour!",
    "settings.integrations.title": "Intégrations",
    "settings.integrations.desc": "Exportez vos politiques directement vers votre espace Notion ou Confluence.",
    "settings.notion.title": "Notion",
    "settings.notion.desc": "Créez une intégration sur {link}, partagez votre page de destination avec elle, puis collez le jeton et l'ID de cette page ci-dessous. Les politiques exportées seront créées comme sous-pages.",
    "settings.notion.token": "Jeton d'intégration interne",
    "settings.notion.parentPageId": "ID de la page parente",
    "settings.notion.parentPageIdHint": "L'ID de 32 caractères à la fin de l'URL de votre page Notion.",
    "settings.notion.save": "Enregistrer les paramètres Notion",
    "settings.notion.saveFailed": "Échec de l'enregistrement des paramètres Notion.",
    "settings.notion.saved": "Notion connecté.",
    "settings.confluence.title": "Confluence",
    "settings.confluence.desc": "Générez un jeton API sur {link}. Les politiques exportées seront créées comme pages dans l'espace ci-dessous.",
    "settings.confluence.siteUrl": "URL du site",
    "settings.confluence.accountEmail": "Courriel du compte",
    "settings.confluence.apiToken": "Jeton API",
    "settings.confluence.spaceKey": "Clé de l'espace",
    "settings.confluence.save": "Enregistrer les paramètres Confluence",
    "settings.confluence.saveFailed": "Échec de l'enregistrement des paramètres Confluence.",
    "settings.confluence.saved": "Confluence connecté.",
    "settings.danger.title": "Zone de danger",
    "settings.danger.desc": "Une fois votre compte supprimé, il n'y a pas de retour en arrière possible. Toutes vos données seront définitivement effacées.",
    "settings.danger.delete": "Supprimer le compte",
    "settings.danger.confirm": "Êtes-vous absolument certain? Cela supprimera définitivement votre compte et toutes vos données. Cette action est irréversible.",
    "settings.danger.contactSupport": "Veuillez contacter le support pour supprimer votre compte.",

    // Relative time
    "time.justNow": "à l'instant",
    "time.minutesAgo": "il y a {n} min",
    "time.hoursAgo": "il y a {n} h",
    "time.daysAgo": "il y a {n} j",

    // Auth pages
    "auth.login.title": "Content de vous revoir!",
    "auth.login.subtitle": "Connectez-vous à votre compte",
    "auth.email": "Courriel",
    "auth.password": "Mot de passe",
    "auth.forgotPassword": "Mot de passe oublié?",
    "auth.signIn": "Se connecter",
    "auth.or": "ou",
    "auth.signInGoogle": "Se connecter avec Google",
    "auth.noAccount": "Vous n'avez pas de compte?",
    "auth.signUp": "S'inscrire",
    "auth.register.title": "Créez votre compte",
    "auth.register.subtitle": "Commencez à générer des politiques de sécurité professionnelles en quelques minutes.",
    "auth.firstName": "Prénom",
    "auth.lastName": "Nom de famille",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.termsAgree": "En créant un compte, vous acceptez nos",
    "auth.termsOfService": "conditions d'utilisation",
    "auth.and": "et notre",
    "auth.privacyPolicy": "politique de confidentialité",
    "auth.createAccount": "Créer un compte",
    "auth.alreadyHaveAccount": "Vous avez déjà un compte?",
    "auth.signInLink": "Se connecter",
    "auth.checkEmail": "Vérifiez votre courriel",
    "auth.confirmationSent": "Nous avons envoyé un lien de confirmation à {email}. Cliquez dessus pour activer votre compte.",
    "auth.backToSignIn": "Retour à la connexion",
    "auth.passwordMismatch": "Les mots de passe ne correspondent pas.",
    "auth.passwordTooShort": "Le mot de passe doit contenir au moins 8 caractères.",
    "auth.reset.title": "Réinitialiser le mot de passe",
    "auth.reset.subtitleDefault": "Entrez votre courriel pour recevoir un lien de réinitialisation.",
    "auth.reset.checkInbox": "Vérifiez votre boîte de réception.",
    "auth.reset.sentTo": "Nous avons envoyé un lien de réinitialisation à {email}.",
    "auth.reset.resend": "Renvoyer le courriel",
    "auth.reset.sendLink": "Envoyer le lien",

    // Error pages
    "notFound.title": "Page introuvable",
    "notFound.desc": "La page que vous cherchez n'existe pas ou a peut-être été déplacée.",
    "notFound.cta": "Retour à l'accueil",
    "error.title": "Une erreur est survenue",
    "error.desc": "Une erreur inattendue s'est produite. Veuillez réessayer — si le problème persiste, contactez le support.",
    "error.retry": "Réessayer",
    "error.cta": "Retour à l'accueil",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("fr");

  useEffect(() => {
    const saved = localStorage.getItem("sp-lang") as Lang | null;
    if (saved === "en" || saved === "fr") setLangState(saved);
  }, []);

  function setLang(l: Lang) {
    setLangState(l);
    localStorage.setItem("sp-lang", l);
  }

  function t(key: string, params?: TParams): string {
    let str = translations[lang][key] ?? translations["en"][key] ?? key;
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        str = str.replace(`{${k}}`, String(v));
      }
    }
    return str;
  }

  const dateLocale = lang === "fr" ? "fr-CA" : "en-CA";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dateLocale }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
