"use client";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Logo } from "@/components/ui/Logo";
import { useLanguage } from "@/contexts/LanguageContext";

export default function TermsPage() {
  const { lang } = useLanguage();

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="border-b border-gray-100 bg-white">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Logo />
          <Link href="/" className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-700">
            <ArrowLeft size={14} /> {lang === "fr" ? "Retour" : "Back"}
          </Link>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-12">
        {lang === "fr" ? <TermsFr /> : <TermsEn />}
      </div>
    </div>
  );
}

function TermsEn() {
  return (
    <article className="prose prose-sm max-w-none prose-headings:font-bold prose-headings:text-gray-900 prose-p:text-gray-600 prose-li:text-gray-600">
      <h1 className="text-2xl! mb-1">Terms of Service</h1>
      <p className="text-xs text-gray-400 mb-8">Last updated: July 2026</p>

      <p>These Terms of Service (&quot;Terms&quot;) govern your access to and use of SecurePilot (&quot;the Service&quot;), operated as a cybersecurity policy and compliance platform for IT consultants and managed service providers. By creating an account or using the Service, you agree to these Terms.</p>

      <h2>1. The Service</h2>
      <p>SecurePilot lets you scan a domain&apos;s public attack surface, generate cybersecurity policy documents with the help of AI, track a security score, and export compliance-related documents on behalf of your own clients. You are responsible for the accuracy of the information you provide and for reviewing any AI-generated document before relying on it or delivering it to a third party.</p>

      <h2>2. Accounts &amp; Subscriptions</h2>
      <p>You must provide accurate registration information and are responsible for activity under your account. Paid plans are billed in advance on a recurring basis through our payment processor (Stripe) and renew automatically until cancelled. You may cancel at any time from your account settings; cancellation takes effect at the end of the current billing period.</p>

      <h2>3. Acceptable Use</h2>
      <p>You agree not to use the Service to scan domains you do not own or are not authorized to assess, to attempt to disrupt or reverse-engineer the Service, or to use it for any unlawful purpose. You are responsible for obtaining any consent required to process your clients&apos; data through the Service.</p>

      <h2>4. Client Data &amp; AI-Generated Content</h2>
      <p>Documents generated by the Service are produced with the assistance of a third-party AI model and are provided as a starting point, not as legal or professional compliance advice. You remain responsible for reviewing, adapting, and validating any generated policy before use. SecurePilot makes no warranty that generated content satisfies any specific regulatory, insurance, or certification requirement.</p>

      <h2>5. Intellectual Property</h2>
      <p>You retain ownership of the data you input and the documents generated for your account. SecurePilot retains all rights to the platform itself, including its software, design, and branding.</p>

      <h2>6. Termination</h2>
      <p>We may suspend or terminate access to the Service for violation of these Terms. You may stop using the Service and delete your account at any time; some data may be retained as required by law or for legitimate business records.</p>

      <h2>7. Disclaimer &amp; Limitation of Liability</h2>
      <p>The Service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law, SecurePilot is not liable for indirect, incidental, or consequential damages arising from your use of the Service, including reliance on AI-generated content.</p>

      <h2>8. Governing Law</h2>
      <p>These Terms are governed by the laws of the Province of Quebec and the applicable federal laws of Canada.</p>

      <h2>9. Changes to These Terms</h2>
      <p>We may update these Terms from time to time. Continued use of the Service after changes take effect constitutes acceptance of the revised Terms.</p>

      <h2>10. Contact</h2>
      <p>Questions about these Terms can be sent to the support address listed in your account.</p>
    </article>
  );
}

function TermsFr() {
  return (
    <article className="prose prose-sm max-w-none prose-headings:font-bold prose-headings:text-gray-900 prose-p:text-gray-600 prose-li:text-gray-600">
      <h1 className="text-2xl! mb-1">Conditions d&apos;utilisation</h1>
      <p className="text-xs text-gray-400 mb-8">Dernière mise à jour : juillet 2026</p>

      <p>Les présentes conditions d&apos;utilisation (les « Conditions ») régissent votre accès et votre utilisation de SecurePilot (le « Service »), une plateforme de politiques de cybersécurité et de conformité destinée aux consultants TI et aux fournisseurs de services gérés. En créant un compte ou en utilisant le Service, vous acceptez les présentes Conditions.</p>

      <h2>1. Le Service</h2>
      <p>SecurePilot vous permet d&apos;analyser la surface d&apos;attaque publique d&apos;un domaine, de générer des documents de politique de cybersécurité à l&apos;aide de l&apos;IA, de suivre un score de sécurité et d&apos;exporter des documents liés à la conformité pour le compte de vos propres clients. Vous êtes responsable de l&apos;exactitude des renseignements que vous fournissez et de la révision de tout document généré par l&apos;IA avant de vous y fier ou de le remettre à un tiers.</p>

      <h2>2. Comptes et abonnements</h2>
      <p>Vous devez fournir des renseignements d&apos;inscription exacts et êtes responsable de l&apos;activité effectuée sous votre compte. Les forfaits payants sont facturés à l&apos;avance de façon récurrente par l&apos;entremise de notre fournisseur de paiement (Stripe) et se renouvellent automatiquement jusqu&apos;à annulation. Vous pouvez annuler en tout temps depuis les paramètres de votre compte; l&apos;annulation prend effet à la fin de la période de facturation en cours.</p>

      <h2>3. Utilisation acceptable</h2>
      <p>Vous acceptez de ne pas utiliser le Service pour analyser des domaines que vous ne possédez pas ou que vous n&apos;êtes pas autorisé à évaluer, de ne pas tenter de perturber ou de faire de l&apos;ingénierie inverse du Service, et de ne pas l&apos;utiliser à des fins illégales. Vous êtes responsable d&apos;obtenir tout consentement requis pour traiter les données de vos clients par l&apos;entremise du Service.</p>

      <h2>4. Données des clients et contenu généré par l&apos;IA</h2>
      <p>Les documents générés par le Service sont produits à l&apos;aide d&apos;un modèle d&apos;IA tiers et constituent un point de départ, et non un avis juridique ou professionnel en matière de conformité. Vous demeurez responsable de la révision, de l&apos;adaptation et de la validation de toute politique générée avant son utilisation. SecurePilot ne garantit pas que le contenu généré satisfait à une exigence réglementaire, d&apos;assurance ou de certification particulière.</p>

      <h2>5. Propriété intellectuelle</h2>
      <p>Vous conservez la propriété des données que vous saisissez et des documents générés pour votre compte. SecurePilot conserve tous les droits sur la plateforme elle-même, y compris son logiciel, son design et son image de marque.</p>

      <h2>6. Résiliation</h2>
      <p>Nous pouvons suspendre ou résilier l&apos;accès au Service en cas de violation des présentes Conditions. Vous pouvez cesser d&apos;utiliser le Service et supprimer votre compte en tout temps; certaines données peuvent être conservées tel que requis par la loi ou pour des dossiers d&apos;affaires légitimes.</p>

      <h2>7. Avis de non-responsabilité et limitation de responsabilité</h2>
      <p>Le Service est fourni « tel quel », sans garantie d&apos;aucune sorte. Dans la mesure maximale permise par la loi, SecurePilot n&apos;est pas responsable des dommages indirects, accessoires ou consécutifs découlant de votre utilisation du Service, y compris du fait de vous être fié à du contenu généré par l&apos;IA.</p>

      <h2>8. Droit applicable</h2>
      <p>Les présentes Conditions sont régies par les lois de la province de Québec et les lois fédérales canadiennes applicables.</p>

      <h2>9. Modifications des présentes Conditions</h2>
      <p>Nous pouvons mettre à jour les présentes Conditions de temps à autre. La poursuite de l&apos;utilisation du Service après l&apos;entrée en vigueur des modifications constitue une acceptation des Conditions révisées.</p>

      <h2>10. Contact</h2>
      <p>Toute question au sujet des présentes Conditions peut être envoyée à l&apos;adresse de soutien indiquée dans votre compte.</p>
    </article>
  );
}
